import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Inter,
  Manufacturing_Consent,
  Merriweather,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fontSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontTitle = Manufacturing_Consent({
  variable: "--font-title",
  weight: "400",
  subsets: ["latin"],
});

const fontMono = Merriweather({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebula News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontMono.variable} ${fontTitle.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-black font-mono">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
